{% set name = "ncbi-datasets-cli" %}
{% set version = "18.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d510c254b56c89458415505bbfbc494c31cb1c828d3599ae92c7585ad231ccfa

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py {{ version }}

requirements:
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://www.ncbi.nlm.nih.gov/datasets
  license: Public Domain
  license_file: LICENSE.md
  summary: NCBI Datasets command-line clients
  doc_url: https://www.ncbi.nlm.nih.gov/datasets/docs/
  description: |
    NCBI Datasets is a resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - corneliusroemer
    - BradHolmes
    - wra3
