{% set name = "ncbi-datasets-cli" %}
{% set version = "13.39.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/release/{{ version }}.tar.gz
  sha256: 89f331009e228099ff89fd0bc7b974ebaf5426ad71a8b78d56fa8b503b269a61

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py

requirements:
  build:
    - bazel <4.0.0
    - go >=1.16.4
    - {{ compiler('cxx') }}
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://www.ncbi.nlm.nih.gov/datasets
  license: Public Domain
  license_file: pkgs/ncbi-datasets-cli/LICENSE.md
  summary: NCBI Datasets command-line clients
  doc_url: https://www.ncbi.nlm.nih.gov/datasets/docs/v1/
  description: |
    NCBI Datasets is a new resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3
