{% set name = "ncbi-datasets-cli" %}
{% set version = "14.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/release/{{ version }}.tar.gz
  sha256: b96533286899affbecc9c8d6192f56046c7d943c468795e7faee2e9095fb8409

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py {{ version }}

requirements:
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://www.ncbi.nlm.nih.gov/datasets
  license: Public Domain
  license_file: pkgs/ncbi-datasets-cli/LICENSE.md
  summary: NCBI Datasets command-line clients
  doc_url: https://www.ncbi.nlm.nih.gov/datasets/docs/v1/
  description: |
    NCBI Datasets is a new resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3
