{% set name = "ncbi-datasets-cli" %}
{% set version = "18.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2722ef5197be2058479a8b12d999e4a3817036fc5e2466a06de2f75b8980dd28

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py {{ version }}

requirements:
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://www.ncbi.nlm.nih.gov/datasets
  license: Public Domain
  license_file: LICENSE.md
  summary: NCBI Datasets command-line clients
  doc_url: https://www.ncbi.nlm.nih.gov/datasets/docs/
  description: |
    NCBI Datasets is a resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - corneliusroemer
    - BradHolmes
    - wra3
